# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ex1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ex1.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tex1.proto\"\x1d\n\rhello_request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0bhello_reply\x12\x0f\n\x07message\x18\x01 \x01(\t25\n\x07greeter\x12*\n\x08sayhello\x12\x0e.hello_request\x1a\x0c.hello_reply\"\x00\x62\x06proto3')
)




_HELLO_REQUEST = _descriptor.Descriptor(
  name='hello_request',
  full_name='hello_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hello_request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=42,
)


_HELLO_REPLY = _descriptor.Descriptor(
  name='hello_reply',
  full_name='hello_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hello_reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['hello_request'] = _HELLO_REQUEST
DESCRIPTOR.message_types_by_name['hello_reply'] = _HELLO_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

hello_request = _reflection.GeneratedProtocolMessageType('hello_request', (_message.Message,), dict(
  DESCRIPTOR = _HELLO_REQUEST,
  __module__ = 'ex1_pb2'
  # @@protoc_insertion_point(class_scope:hello_request)
  ))
_sym_db.RegisterMessage(hello_request)

hello_reply = _reflection.GeneratedProtocolMessageType('hello_reply', (_message.Message,), dict(
  DESCRIPTOR = _HELLO_REPLY,
  __module__ = 'ex1_pb2'
  # @@protoc_insertion_point(class_scope:hello_reply)
  ))
_sym_db.RegisterMessage(hello_reply)



_GREETER = _descriptor.ServiceDescriptor(
  name='greeter',
  full_name='greeter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=76,
  serialized_end=129,
  methods=[
  _descriptor.MethodDescriptor(
    name='sayhello',
    full_name='greeter.sayhello',
    index=0,
    containing_service=None,
    input_type=_HELLO_REQUEST,
    output_type=_HELLO_REPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
