# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ex1_pb2 as ex1__pb2


class greeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sayhello = channel.unary_unary(
        '/greeter/sayhello',
        request_serializer=ex1__pb2.hello_request.SerializeToString,
        response_deserializer=ex1__pb2.hello_reply.FromString,
        )


class greeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sayhello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_greeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sayhello': grpc.unary_unary_rpc_method_handler(
          servicer.sayhello,
          request_deserializer=ex1__pb2.hello_request.FromString,
          response_serializer=ex1__pb2.hello_reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
